language: python
python: "2.7"

env:
  - TOX_ENV=py27-django16-pg
  - TOX_ENV=py27-django16-sqlite
  - TOX_ENV=py27-django17-pg
  - TOX_ENV=py27-django17-sqlite
  - TOX_ENV=py34-django16-pg
  - TOX_ENV=py34-django16-sqlite
  - TOX_ENV=py34-django17-pg
  - TOX_ENV=py34-django17-sqlite

# Enable PostgreSQL usage
addons:
  - postgresql: "9.3"

# Dependencies
install:
  - pip install tox
  - pip install coveralls

# Ensure PostgreSQL-DB to be configured correctly
before_script:
  - cp -f cleanerversion/settings/pg_travis.py cleanerversion/settings/pg.py
  - psql -c 'alter user postgres createdb;' -U postgres

# Run tests
script:
  tox -e $TOX_ENV

# Run coveralls
after_success:
  coveralls
