language: python
python:
  - "2.7"
  - "3.6"

# Enable PostgreSQL usage
addons:
  postgresql: "9.3"

# Dependencies
install:
  - pip install tox
  - pip install tox-travis
  - pip install coveralls

# Ensure PostgreSQL-DB to be configured correctly
before_script:
  - cp -f cleanerversion/settings/pg_travis.py cleanerversion/settings/pg.py
  - psql -c 'alter user postgres createdb;' -U postgres
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test with owner postgres;' -U postgres

# Run tests
script:
  tox

# Run coveralls
after_success:
  coveralls
