language: python
python: "2.7"

env:
  - TOX_ENV=py27-django18-pg
  - TOX_ENV=py27-django18-sqlite
  - TOX_ENV=py27-django19-pg
  - TOX_ENV=py27-django19-sqlite
  - TOX_ENV=py34-django18-pg
  - TOX_ENV=py34-django18-sqlite
  - TOX_ENV=py34-django19-pg
  - TOX_ENV=py34-django19-sqlite

# Enable PostgreSQL usage
addons:
  postgresql: "9.3"

# Dependencies
install:
  - pip install tox
  - pip install coveralls

# Ensure PostgreSQL-DB to be configured correctly
before_script:
  - cp -f cleanerversion/settings/pg_travis.py cleanerversion/settings/pg.py
  - psql -c 'alter user postgres createdb;' -U postgres
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test with owner postgres;' -U postgres

# Run tests
script:
  tox -e $TOX_ENV

# Run coveralls
after_success:
  coveralls
