language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

# Dependencies
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install six
  - pip install coveralls

# Run tests
script:
  coverage run --source=versions ./manage.py test

# Run coveralls
after_success:
  coveralls
